

variable "vpc_id" {
  type = string
}

variable "region" {
  type    = string
  default = "us-east-2"
}

variable "subnet_id" {
  type = string
}

variable "instance_type" {
  type    = string
  default = "t2.micro"
}

variable "volume_size" {
  type    = string
  default = "20"
}

variable "baseos_name" {
  type    = string
  default = "CentOS"
}

variable "baseos_sshuser" {
  type    = string
  default = "centos"
}

variable "baseos_version" {
  type    = string
  default = "7.9.2009"
}

variable "baseos_owner" {
  type    = string
  default = "125523088429" #CentOS
}

variable "baseos_arch" {
  type    = string
  default = "x86_64"
}

variable "owner_name" {
  type        = string
  description = "Owner of the new AMI generated by Packer"
}

variable "purpose" {
  type    = string
  default = "custom"
}

